from .endpoints.alerts import TestAlertsEndpoint
from .endpoints.glossary import TestGlossaryEndpoint
from .endpoints.gridpoints import TestGridpointsEndpoint
from .endpoints.icons import TestIconsEndpoint
from .endpoints.offices import TestOfficesEndpoint
from .endpoints.points import TestPointsEndpoint
from .endpoints.products import TestProductsEndpoint
from .endpoints.stations import TestStationsEndpoint
from .endpoints.thumbnails import TestThumbnailsEndpoint
from .endpoints.zones import TestZonesEndpoint
